### ISSUE TITLE
Preset form values (from bound object) are not used if you submit another form

### ISSUE THREAD

**Issue by bweinzierl** [neos/fusion-form#48]
Szenario:
Have two different forms on one page. Bind the forms to an object so that the fields are filled form properties of that object.
If you now submit one of the forms and you have validation errors the values in the not submitted form are cleared.

The Method `field.findCurrentValueByPath()` returns NULL for every form field of the unsubmitted form.
Thats because `$this->form->getResult()->hasErrors()` is true for both forms and not just for the form that got submitted.

Expected Behaviour:
All form fields of the form that has not been touched should still display the properties of the bound object.

**Comment by mficzel** [comment]
I confirm the issue
