### ISSUE TITLE
Export documentation?

### ISSUE THREAD

**Issue by kitsunet** [neos/fusion-form#91]
Just wanted to look up something in a local install and noticed the documentation is missing, due to the .gitignore config. Any particular reason to not include it? This way the readme is there but points to missing files which is a bit unfortunate :D

**Comment by bwaidelich** [comment]
[.gitignore](https://github.com/neos/fusion-form/blob/75e08003fd1d0fa2236dea719f0528bd3ed63483/.gitignore) does not contain docs, why is it excluded?

**Comment by jonnitto** [comment]
It's not in the `.gitignore`, it is in `.gitattributes`
